### ISSUE TITLE
Enabling Realsense Camera

### ISSUE THREAD

**Issue by lpmrz** [ctu-mrs/mrs_uav_system#37] opened 2021-01-30 08:48 UTC
Hello,

I am trying to use PointCloud2 data for 3D mapping purposes. What I have done so far:

- I saw that it is being published under the topic /uav1/os1_cloud_node/points. However no node seems to publish it. I tried to enable Realsense camera by adding the following parameter (--enable-realsense-front-pitched)to the session.yaml. If the drone is supporting it, simulation launches without errors. But Realsense came does not appear to be working.

Here is the status window:

[Image of Status Window](https://pasteboard.co/JM0DFfl.png)

I think I am missing something. Do you have any recommendations?

**Comment by DanHert** [comment] 2021-02-01 14:32
Hello, the problem is not that the realsense is not working, but the status window is checking a wrong topic. I fixed the status node, so now it should display the realsense correctly. I also fixed the duplication of the Garmin topic.

Pull uav_core and recompile and the status should be displayed correctly. But the realsense was working all along.

**Comment by lpmrz** [comment] 2021-02-01 16:34
Thank you for your help. I pulled the uav_core and did a catkin build. But now there is this error:
![Screenshot from 2021-02-01 19-31-38](https://user-images.githubusercontent.com/18270807/106488217-86087180-64c4-11eb-9459-218caeabc190.png)

**Comment by DanHert** [comment] 2021-02-03 12:47
Hi, I dont have any problems with the simulation, so probably just going to ~/mrs_workspace and calling
`catkin clean`
`catkin build`
should fix this.

**Comment by lpmrz** [comment] 2021-02-04 08:32
Thank you very much. I cleaned and built again, now Realsense and the status are working perfectly. Unfortunately I can't obtain any PointCloud2 data. I type _rostopic find sensor_msgs/PointCloud2_ and it returns:

- /uav1/bumper/lidar3d_processed
- /octomap_point_cloud_centers
- /uav1/os1_cloud_node/points

When I type _rostopic echo /uav1/bumper/lidar3d_processed_ it publishes nothing. Others return empty too. Do I have to do something extra for those topics to start publishing?

Thank you again for your time and interest.

**Comment by DanHert** [comment] 2021-02-04 08:45
Hello, our simulated realsense does not produce any point cloud messages. It produces a depth image on a topic
`/$UAV_NAME/rs_d435/aligned_depth_to_color/image_raw`
You can either modify the simulation plugin to publish point clouds, or use this package - http://wiki.ros.org/depth_image_proc
to convert the depth images into point clouds.

**Comment by WingRS** [comment] 2021-03-09 07:40
Hi all,
By my opinion Dan has provided a nice explanation of the PCL, I am closing the issue. 
Thanks to all. :)

**Closed by WingRS** 2021-03-09 07:40 UTC
